name: "Setup S3 Static Site"
description: "Setup static site for test prs"
inputs:
  repo-token:
    required: true
outputs:
  url:
    description: "URL to newly created bucket"
runs:
  using: "node12"
  main: "index.js"
