name: Delete S3 Static Site
on:
  # pull_request
  push:
    branches:
      - master
  pull_request:
    branches:
      - "!master"
    types: [closed]

jobs:
  delete-bucket:
    name: S3 Delete Bucket
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: sandbox
          path: artifact/sandbox.txt
      - name: Read artifact
        id: artifact
        run: |
          read -r bucketName<artifact/sandbox.txt
          echo "::set-output name=bucketName::$bucketName"
      - name: Delete bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # run: aws s3 rb s3://${{ github.actor }}-${{ github.head_ref }} --force
        run: |
          echo " ${{ steps.artifact.outputs.bucketName }}"
