name: Delete S3 Static Site
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "!master"
    types: [closed]

jobs:
  delete-bucket:
    name: S3 Delete Bucket
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Delete bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # run: aws s3 rb s3://${{ github.actor }}-${{ github.head_ref }} --force
        run: |
          echo "base: ${{ github.base_ref }} head: ${{ github.head_ref }}"
