name: S3 Static Site
on: pull_request

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create S3 Site
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        id: s3
        uses: ./
        with:
          build-dir: "build"
      - name: S3 URL
        run: echo ${{ steps.s3.outputs.url }}
